# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('setting_type', models.CharField(choices=[('INTEGER', 'Número Entero'), ('FLOAT', 'Número Decimal'), ('STRING', 'Texto'), ('BOOLEAN', 'Verdadero/Falso'), ('JSON', 'JSON')], max_length=20, verbose_name='Tipo de Configuración')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuraciones de Plataforma',
                'db_table': 'platform_settings',
                'ordering': ['key'],
            },
        ),
    ]
