# Generated by Django 4.2.7 on 2025-01-08 23:02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('setting_type', models.CharField(choices=[('string', 'Texto'), ('number', 'Número'), ('boolean', 'Booleano'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo de configuración')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración de plataforma',
                'verbose_name_plural': 'Configuraciones de plataforma',
                'db_table': 'platform_settings_platformsetting',
                'ordering': ['key'],
            },
        ),
    ] 