# Generated by Django 4.2.7 on 2025-08-05 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_backups", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL para reconocer la tabla existente
            reverse_sql="SELECT 1;"
        ),
    ]
