# Generated by Django 4.2.7 on 2025-08-06 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_backups", "0002_auto_20250805_1437"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="databackups",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Respaldo de Datos",
                "verbose_name_plural": "Respaldos de Datos",
            },
        ),
        migrations.RemoveField(
            model_name="databackups",
            name="description",
        ),
        migrations.RemoveField(
            model_name="databackups",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="databackups",
            name="name",
        ),
        migrations.RemoveField(
            model_name="databackups",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="databackups",
            name="backup_name",
            field=models.CharField(default="Backup automático", max_length=200),
        ),
        migrations.AddField(
            model_name="databackups",
            name="backup_type",
            field=models.CharField(
                choices=[
                    ("full", "Completo"),
                    ("incremental", "Incremental"),
                    ("differential", "Diferencial"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="databackups",
            name="checksum",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="databackups",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="databackups",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_backups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="databackups",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="databackups",
            name="file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="databackups",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="databackups",
            name="file_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="databackups",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("processing", "Procesando"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                    ("expired", "Expirado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="databackups",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="databackups",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="databackups",
            table="data_backups",
        ),
    ]
