# Generated by Django 3.2.23 on 2025-06-20 17:18

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to='users.customuser')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='Universidad')),
                ('major', models.CharField(blank=True, max_length=255, verbose_name='Carrera')),
                ('semester', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semestre')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('skills', models.TextField(blank=True, help_text='Separar habilidades por comas', verbose_name='Habilidades')),
                ('linkedin_profile', models.URLField(blank=True, verbose_name='Perfil de LinkedIn')),
                ('cv', models.FileField(blank=True, null=True, upload_to=students.models.student_cv_path, verbose_name='Currículum Vitae')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
