# Generated by Django 4.2.7 on 2025-09-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="rut",
            field=models.CharField(
                blank=True,
                help_text="RUT del estudiante",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="section",
            field=models.CharField(
                blank=True, help_text="Sección del estudiante", max_length=50, null=True
            ),
        ),
    ]
