# Generated by Django 4.2.23 on 2025-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
