# Generated by Django 4.2.7 on 2025-09-15 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_estudiante_rut_estudiante_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="rut",
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="section",
        ),
    ]
