# Generated by Django 4.2.7 on 2025-07-16 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_apilevelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='trl_level',
            field=models.IntegerField(default=1, help_text='Nivel TRL del 1 al 9 según el estado del proyecto', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
