# Generated by Django 4.2.7 on 2025-07-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_estudiante_trl_level_alter_estudiante_gpa"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="certificado_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="cv_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
