# Generated by Django 4.2.7 on 2025-07-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_add_document_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="area",
            field=models.CharField(
                blank=True,
                help_text="Área de interés del estudiante",
                max_length=200,
                null=True,
            ),
        ),
    ]
