# Generated by Django 4.2.7 on 2025-07-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_alter_apilevelrequest_id_alter_estudiante_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                    ("suspended", "Suspendido"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
    ]
