# Generated by Django 4.2.7 on 2025-08-10 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0009_change_student_status_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="rating",
        ),
    ]
