# Generated by Django 4.2.7 on 2025-08-13 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0011_estudiante_hours_per_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="graduation_year",
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="languages",
        ),
    ]
