# Generated by Django 4.2.7 on 2025-08-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0013_populate_hours_per_week_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="api_level_approved_by_admin",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el nivel API fue aprobado manualmente por admin",
            ),
        ),
    ]
