# Generated by Django 4.2.7 on 2025-07-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
