# Generated by Django 4.2.7 on 2025-07-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_passwordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
