# Generated by Django 4.2.7 on 2025-08-06 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_auto_20250805_1437"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reports",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
            },
        ),
        migrations.RemoveField(
            model_name="reports",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="reports",
            name="name",
        ),
        migrations.RemoveField(
            model_name="reports",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="reports",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reports",
            name="file_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="reports",
            name="report_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reports",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("student", "Estudiante"),
                    ("company", "Empresa"),
                    ("project", "Proyecto"),
                    ("evaluation", "Evaluación"),
                    ("financial", "Financiero"),
                    ("analytics", "Analíticas"),
                    ("system", "Sistema"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="reports",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("processing", "Procesando"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reports",
            name="title",
            field=models.CharField(default="Reporte del sistema", max_length=200),
        ),
        migrations.AlterField(
            model_name="reports",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reports",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reports",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="reports",
            table="reports",
        ),
    ]
