# Generated by Django 4.2.23 on 2025-01-27 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_consolidated'),
        ('students', '0001_initial_consolidated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('strike_type', models.CharField(choices=[('minor', 'Menor'), ('major', 'Mayor'), ('critical', 'Crítico')], default='minor', max_length=20)),
                ('severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes_issued', to='users.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='students.estudiante')),
            ],
            options={
                'verbose_name': 'Strike',
                'verbose_name_plural': 'Strikes',
                'db_table': 'strikes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrikeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('strike_appeal', 'Apelación de Strike'), ('strike_report', 'Reporte de Strike'), ('other', 'Otro')], default='strike_report', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('resolved', 'Resuelto'), ('dismissed', 'Desestimado')], default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to='users.user')),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strike_reports', to='users.user')),
                ('related_strike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='strikes.strike')),
            ],
            options={
                'verbose_name': 'Reporte de Strike',
                'verbose_name_plural': 'Reportes de Strikes',
                'db_table': 'strike_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
