# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('project_published', 'Proyecto Publicado'), ('project_updated', 'Proyecto Actualizado'), ('project_cancelled', 'Proyecto Cancelado'), ('project_completed', 'Proyecto Completado'), ('application_submitted', 'Aplicación Enviada'), ('application_reviewed', 'Aplicación Revisada'), ('application_accepted', 'Aplicación Aceptada'), ('application_rejected', 'Aplicación Rechazada'), ('application_withdrawn', 'Aplicación Retirada'), ('interview_scheduled', 'Entrevista Programada'), ('interview_reminder', 'Recordatorio de Entrevista'), ('interview_cancelled', 'Entrevista Cancelada'), ('evaluation_received', 'Evaluación Recibida'), ('evaluation_requested', 'Evaluación Solicitada'), ('evaluation_completed', 'Evaluación Completada'), ('system_announcement', 'Anuncio del Sistema'), ('maintenance_notice', 'Aviso de Mantenimiento'), ('feature_update', 'Actualización de Funcionalidad'), ('strike_received', 'Strike Recibido'), ('strike_warning', 'Advertencia de Strike'), ('strike_suspension', 'Suspensión por Strikes'), ('hours_submitted', 'Horas Enviadas'), ('hours_approved', 'Horas Aprobadas'), ('hours_rejected', 'Horas Rechazadas'), ('profile_updated', 'Perfil Actualizado'), ('verification_completed', 'Verificación Completada'), ('api_level_upgraded', 'Nivel de API Mejorado'), ('new_message', 'Nuevo Mensaje'), ('message_reply', 'Respuesta a Mensaje'), ('event_reminder', 'Recordatorio de Evento'), ('event_cancelled', 'Evento Cancelado'), ('event_updated', 'Evento Actualizado')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled_types', models.JSONField(default=list)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Inmediato'), ('hourly', 'Cada hora'), ('daily', 'Diario'), ('weekly', 'Semanal')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('notification_type', models.CharField(choices=[('project_published', 'Proyecto Publicado'), ('project_updated', 'Proyecto Actualizado'), ('project_cancelled', 'Proyecto Cancelado'), ('project_completed', 'Proyecto Completado'), ('application_submitted', 'Aplicación Enviada'), ('application_reviewed', 'Aplicación Revisada'), ('application_accepted', 'Aplicación Aceptada'), ('application_rejected', 'Aplicación Rechazada'), ('application_withdrawn', 'Aplicación Retirada'), ('interview_scheduled', 'Entrevista Programada'), ('interview_reminder', 'Recordatorio de Entrevista'), ('interview_cancelled', 'Entrevista Cancelada'), ('evaluation_received', 'Evaluación Recibida'), ('evaluation_requested', 'Evaluación Solicitada'), ('evaluation_completed', 'Evaluación Completada'), ('system_announcement', 'Anuncio del Sistema'), ('maintenance_notice', 'Aviso de Mantenimiento'), ('feature_update', 'Actualización de Funcionalidad'), ('strike_received', 'Strike Recibido'), ('strike_warning', 'Advertencia de Strike'), ('strike_suspension', 'Suspensión por Strikes'), ('hours_submitted', 'Horas Enviadas'), ('hours_approved', 'Horas Aprobadas'), ('hours_rejected', 'Horas Rechazadas'), ('profile_updated', 'Perfil Actualizado'), ('verification_completed', 'Verificación Completada'), ('api_level_upgraded', 'Nivel de API Mejorado'), ('new_message', 'Nuevo Mensaje'), ('message_reply', 'Respuesta a Mensaje'), ('event_reminder', 'Recordatorio de Evento'), ('event_cancelled', 'Evento Cancelado'), ('event_updated', 'Evento Actualizado')], max_length=30)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('available_variables', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
                'db_table': 'notification_templates',
                'unique_together': {('name', 'notification_type')},
            },
        ),
    ]
