# Generated by Django 5.2.3 on 2025-06-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_583549_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_19df93_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_created_e4c995_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='scheduled_for',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_application',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_project',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        # migrations.AlterField(
        #     model_name='notification',
        #     name='id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('reminder', 'Recordatorio'), ('alert', 'Alerta'), ('info', 'Información'), ('warning', 'Advertencia'), ('success', 'Éxito'), ('error', 'Error')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='enabled_types',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='available_variables',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('reminder', 'Recordatorio'), ('alert', 'Alerta'), ('info', 'Información'), ('warning', 'Advertencia'), ('success', 'Éxito'), ('error', 'Error')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10),
        ),
    ]
