# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo de la Amonestación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_strikes', to='companies.empresa', verbose_name='Empresa Emisora')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Amonestación (Strike)',
                'verbose_name_plural': 'Amonestaciones (Strikes)',
                'db_table': 'strikes',
                'ordering': ['-created_at'],
            },
        ),
    ]
