# Generated by Django 4.2.23 on 2025-07-02 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='Motivo de la Amonestación')),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_strikes', to='companies.empresa', verbose_name='Empresa Emisora')),
            ],
            options={
                'verbose_name': 'Amonestación (Strike)',
                'verbose_name_plural': 'Amonestaciones (Strikes)',
                'db_table': 'strikes',
                'ordering': ['-issued_at'],
            },
        ),
    ]
