# Generated by Django 4.2.23 on 2025-07-02 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strikes_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strike',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strike_records', to='students.estudiante', verbose_name='Estudiante'),
        ),
    ]
