# Generated by Django 3.2.23 on 2025-06-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strikes', '0001_initial'),
        ('projects', '0002_initial'),
        ('students', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_strikes', to='companies.company', verbose_name='Empresa Emisora'),
        ),
        migrations.AddField(
            model_name='strike',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='strike',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='students.student', verbose_name='Estudiante'),
        ),
    ]
