# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('strikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='students.estudiante', verbose_name='Estudiante'),
        ),
    ]
