# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strikes', '0002_strike_student'),
        ('students', '0002_alter_estudiante_options_remove_estudiante_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strike',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Amonestación (Strike)', 'verbose_name_plural': 'Amonestaciones (Strikes)'},
        ),
        migrations.RenameField(
            model_name='strike',
            old_name='created_at',
            new_name='issued_at',
        ),
        migrations.RemoveField(
            model_name='strike',
            name='project',
        ),
        migrations.AddField(
            model_name='strike',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='strike',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strikes_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strike',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strike',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strike',
            name='severity',
            field=models.CharField(default='medium', max_length=20),
        ),
        # migrations.AlterField(
        #     model_name='strike',
        #     name='id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='strike',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strike_records', to='students.estudiante', verbose_name='Estudiante'),
        ),
    ]
