# Generated by Django 4.2.7 on 2025-09-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collective_challenges", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="challenge_end",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="challenge_start",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="current_teams",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="duration_weeks",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="encargado",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="evaluation_criteria",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="hours_per_week",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="judges",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="max_teams",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="modality",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="preferred_skills",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="prizes",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="registration_end",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="registration_start",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="students_per_team",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="total_hours",
        ),
        migrations.RemoveField(
            model_name="desafiocolectivo",
            name="total_students_needed",
        ),
        migrations.AlterField(
            model_name="desafiocolectivo",
            name="academic_year",
            field=models.CharField(help_text="Año académico (ej: 2024)", max_length=10),
        ),
        migrations.AlterField(
            model_name="desafiocolectivo",
            name="contacto",
            field=models.CharField(
                blank=True,
                help_text="Información de contacto",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="desafiocolectivo",
            name="objetivo",
            field=models.TextField(
                blank=True, help_text="Criterios de evaluación", null=True
            ),
        ),
        migrations.AlterField(
            model_name="desafiocolectivo",
            name="period_type",
            field=models.CharField(
                choices=[("trimestral", "Trimestral"), ("semestral", "Semestral")],
                default="trimestral",
                help_text="Tipo de período académico",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="desafiocolectivo",
            name="requirements",
            field=models.TextField(help_text="Contexto completo del problema"),
        ),
        migrations.AlterField(
            model_name="desafiocolectivo",
            name="tipo",
            field=models.CharField(
                blank=True, help_text="Recursos disponibles", max_length=200, null=True
            ),
        ),
    ]
