# Generated by Django 4.2.7 on 2025-09-13 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "collective_challenges",
            "0003_challengearea_teachersection_studentgroup_and_more",
        ),
    ]

    operations = []
