# Generated by Django 4.2.7 on 2025-09-15 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collective_challenges", "0004_auto_20250913_0700"),
        ("collective_challenges", "0005_rename_trl_to_trld"),
    ]

    operations = []
