# Generated by Django 4.2.7 on 2025-09-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "collective_challenges",
            "0006_merge_0004_auto_20250913_0700_0005_rename_trl_to_trld",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengeprogress",
            name="responses_data",
            field=models.TextField(
                blank=True,
                help_text="Respuestas a las preguntas TRLD (JSON)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengequestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("trld_1", "TRLD 1 - Identificación del Problema"),
                    ("trld_2", "TRLD 2 - Análisis de Requerimientos"),
                    ("trld_3", "TRLD 3 - Diseño Conceptual"),
                    ("trld_4", "TRLD 4 - Planificación de Desarrollo"),
                    ("trld_5", "TRLD 5 - Implementación Inicial"),
                    ("trld_6", "TRLD 6 - Pruebas y Validación"),
                    ("trld_7", "TRLD 7 - Optimización y Mejoras"),
                    ("trld_8", "TRLD 8 - Documentación y Entrega"),
                    ("trld_9", "TRLD 9 - Evaluación Final y Retroalimentación"),
                ],
                help_text="Tipo de pregunta TRL",
                max_length=10,
            ),
        ),
    ]
