# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del estado', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del estado', null=True)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal del estado', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Proyecto',
                'verbose_name_plural': 'Estados de Proyecto',
                'db_table': 'project_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='projects.proyecto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='project_status.projectstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_status_history',
            },
        ),
    ]
