# Generated by Django 4.2.23 on 2025-07-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del estado', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del estado', null=True)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal del estado', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Proyecto',
                'verbose_name_plural': 'Estados de Proyecto',
                'db_table': 'project_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_status_history',
            },
        ),
    ]
