# Generated by Django 4.2.7 on 2025-08-19 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("project_status", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectstatushistory",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="projects.proyecto",
            ),
        ),
        migrations.AddField(
            model_name="projectstatushistory",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="project_status.projectstatus",
            ),
        ),
        migrations.AddField(
            model_name="projectstatushistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
