# Generated by Django 3.2.23 on 2025-06-28 17:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carta_presentacion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisando', 'En Revisión'), ('entrevistado', 'Entrevistado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('retirado', 'Retirado'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('puntaje_compatibilidad', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('notas_empresa', models.TextField(blank=True, null=True)),
                ('notas_estudiante', models.TextField(blank=True, null=True)),
                ('url_portfolio', models.URLField(blank=True, null=True)),
                ('url_github', models.URLField(blank=True, null=True)),
                ('url_linkedin', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aplicación a Proyecto',
                'verbose_name_plural': 'Aplicaciones a Proyectos',
                'db_table': 'project_applications',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='MiembroProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('mentor', 'Mentor'), ('supervisor', 'Supervisor'), ('coordinador', 'Coordinador')], default='estudiante', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('horas_trabajadas', models.PositiveIntegerField(default=0)),
                ('tareas_completadas', models.PositiveIntegerField(default=0)),
                ('evaluacion_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('es_verificado', models.BooleanField(default=False)),
                ('responsabilidades', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Miembro del Proyecto',
                'verbose_name_plural': 'Miembros del Proyecto',
                'db_table': 'project_members',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('remoto', 'Remoto'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], default='remoto', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('dificultad', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='intermedio', max_length=20)),
                ('habilidades_requeridas', models.JSONField(default=list)),
                ('habilidades_preferidas', models.JSONField(default=list)),
                ('nivel_api_minimo', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('duracion_meses', models.PositiveIntegerField(default=3)),
                ('horas_por_semana', models.PositiveIntegerField(default=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_pagado', models.BooleanField(default=False)),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda_pago', models.CharField(default='USD', max_length=3)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pausado', 'Pausado')], default='borrador', max_length=20)),
                ('max_estudiantes', models.PositiveIntegerField(default=1)),
                ('estudiantes_actuales', models.PositiveIntegerField(default=0)),
                ('aplicaciones_count', models.PositiveIntegerField(default=0)),
                ('vistas_count', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('es_destacado', models.BooleanField(default=False)),
                ('es_urgente', models.BooleanField(default=False)),
                ('etiquetas', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
