# Generated by Django 4.2.23 on 2025-07-02 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_status', '0003_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroproyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestadosproyecto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='projects.proyecto'),
        ),
        migrations.AddField(
            model_name='historialestadosproyecto',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='project_status.projectstatus'),
        ),
        migrations.AddField(
            model_name='historialestadosproyecto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado_proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacionproyecto',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacionproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to='projects.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='miembroproyecto',
            unique_together={('proyecto', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='aplicacionproyecto',
            unique_together={('proyecto', 'estudiante')},
        ),
    ]
