# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miembroproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='projects.proyecto'),
        ),
        migrations.AddField(
            model_name='miembroproyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacionproyecto',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacionproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='projects.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='miembroproyecto',
            unique_together={('proyecto', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='aplicacionproyecto',
            unique_together={('proyecto', 'estudiante')},
        ),
    ]
