# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('companies', '0003_rename_persona_contacto_empresa_city_and_more'),
        ('project_status', '0001_initial'),
        ('projects', '0002_initial'),
        ('trl_levels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='es_destacado',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='es_pagado',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='es_urgente',
            new_name='is_urgent',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='ubicacion',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='monto_pago',
            new_name='payment_amount',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='moneda_pago',
            new_name='payment_currency',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_publicacion',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='aplicaciones_count',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='duracion_meses',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='estudiantes_actuales',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='habilidades_preferidas',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='habilidades_requeridas',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='horas_por_semana',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='max_estudiantes',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nivel_api_minimo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='vistas_count',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='api_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='applications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='current_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='duration_months',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='hours_per_week',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='max_students',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='min_api_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='modality',
            field=models.CharField(choices=[('remote', 'Remoto'), ('onsite', 'Presencial'), ('hybrid', 'Híbrido')], default='remote', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='preferred_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='real_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='required_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='project_status.projectstatus'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='trl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='trl_levels.trllevel'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aplicacionproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to='projects.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='areas.area'),
        ),
        migrations.CreateModel(
            name='HistorialEstadosProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='projects.proyecto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='project_status.projectstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado de Proyecto',
                'verbose_name_plural': 'Historial de Estados de Proyectos',
                'db_table': 'project_status_changes',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
