# Generated by Django 4.2.7 on 2025-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_proyecto_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Principiante"),
                    ("intermediate", "Intermedio"),
                    ("intermediate-advanced", "Intermedio-Avanzado"),
                    ("advanced", "Avanzado"),
                ],
                default="intermediate",
                max_length=25,
            ),
        ),
    ]
