# Generated by Django 4.2.7 on 2025-07-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_proyecto_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="contacto",
            field=models.CharField(
                blank=True,
                help_text="Contacto de la empresa",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="encargado",
            field=models.CharField(
                blank=True,
                help_text="Responsable del proyecto de la empresa",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="objetivo",
            field=models.TextField(
                blank=True, help_text="Objetivo del proyecto", null=True
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tipo",
            field=models.CharField(
                blank=True,
                help_text="Tipo de actividad del proyecto",
                max_length=100,
                null=True,
            ),
        ),
    ]
