# Generated by Django 4.2.7 on 2025-08-03 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_proyecto_is_project_completion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="difficulty",
        ),
    ]
