# Generated by Django 4.2.7 on 2025-08-19 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Pregunta")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("number", "Número"),
                            ("select", "Selección única"),
                            ("multiselect", "Selección múltiple"),
                            ("boolean", "Sí/No"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Tipo de pregunta",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="Obligatoria"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "db_table": "questionnaires_question",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuestionario",
                "verbose_name_plural": "Cuestionarios",
                "db_table": "questionnaires_questionnaire",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_responses",
                        to="projects.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="questionnaires.questionnaire",
                        verbose_name="Cuestionario",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_responses",
                        to="students.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de cuestionario",
                "verbose_name_plural": "Respuestas de cuestionarios",
                "db_table": "questionnaires_questionnaireresponse",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Opción")),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questionnaires.question",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de pregunta",
                "verbose_name_plural": "Opciones de pregunta",
                "db_table": "questionnaires_questionoption",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Respuesta de texto"
                    ),
                ),
                (
                    "number_response",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Respuesta numérica",
                    ),
                ),
                (
                    "boolean_response",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Respuesta booleana"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="questionnaires.question",
                        verbose_name="Pregunta",
                    ),
                ),
                (
                    "questionnaire_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_responses",
                        to="questionnaires.questionnaireresponse",
                        verbose_name="Respuesta de cuestionario",
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(
                        blank=True,
                        to="questionnaires.questionoption",
                        verbose_name="Opciones seleccionadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de pregunta",
                "verbose_name_plural": "Respuestas de preguntas",
                "db_table": "questionnaires_questionresponse",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questionnaires.questionnaire",
                verbose_name="Cuestionario",
            ),
        ),
    ]
