# Generated by Django 4.2.7 on 2025-07-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0002_alter_calendarevent_related_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10),
        ),
    ]
