# Generated by Django 4.2.7 on 2025-08-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0003_alter_calendarevent_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="meeting_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="meeting_room",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="meeting_type",
            field=models.CharField(
                blank=True,
                choices=[("online", "Online"), ("onsite", "En Sede")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="representative_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="representative_position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
