# Generated by Django 4.2.7 on 2025-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0004_calendarevent_meeting_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="meeting_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("cowork", "Cowork"),
                    ("fablab", "FabLab"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
