# Generated by Django 4.2.7 on 2025-08-12 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0005_alter_calendarevent_meeting_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventReminder",
        ),
    ]
