# Generated by Django 4.2.23 on 2025-07-02 01:37

from django.db import migrations, models


def create_initial_project_statuses(apps, schema_editor):
    """Crear los estados iniciales de proyectos"""
    ProjectStatus = apps.get_model('project_status', 'ProjectStatus')
    
    # Estados de proyectos
    statuses = [
        {
            'name': 'published',
            'description': 'El proyecto está publicado y visible para los estudiantes',
            'color': '#1976d2'
        },
        {
            'name': 'active',
            'description': 'El proyecto está en curso y los estudiantes están trabajando en él',
            'color': '#388e3c'
        },
        {
            'name': 'completed',
            'description': 'El proyecto ha sido finalizado exitosamente',
            'color': '#fbc02d'
        },
        {
            'name': 'deleted',
            'description': 'El proyecto ha sido eliminado',
            'color': '#d32f2f'
        },
        {
            'name': 'draft',
            'description': 'El proyecto está en borrador',
            'color': '#757575'
        }
    ]
    
    for status_data in statuses:
        ProjectStatus.objects.create(**status_data)


def reverse_create_initial_project_statuses(apps, schema_editor):
    """Eliminar los estados iniciales de proyectos"""
    ProjectStatus = apps.get_model('project_status', 'ProjectStatus')
    ProjectStatus.objects.filter(name__in=['published', 'active', 'completed', 'deleted', 'draft']).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del estado', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del estado', null=True)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal del estado', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Proyecto',
                'verbose_name_plural': 'Estados de Proyecto',
                'db_table': 'project_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_status_history',
            },
        ),
        # Agregar los datos iniciales
        migrations.RunPython(create_initial_project_statuses, reverse_create_initial_project_statuses),
    ]
