# Generated by Django 3.2.23 on 2025-06-20 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('companies', '0001_initial'),
        ('projects', '0002_project_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_type', models.CharField(choices=[('COMPANY', 'Empresa'), ('STUDENT', 'Estudiante')], max_length=10, verbose_name='Tipo de Evaluador')),
                ('evaluator_id', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5)')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to='companies.company', verbose_name='Empresa Evaluada')),
                ('evaluated_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to='students.student', verbose_name='Estudiante Evaluado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'evaluator_type', 'evaluator_id', 'evaluated_company'), ('project', 'evaluator_type', 'evaluator_id', 'evaluated_student')},
            },
        ),
    ]
