# Generated by Django 4.2.7 on 2025-07-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_alter_evaluation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('flagged', 'Marcada')], default='pending', max_length=20),
        ),
    ]
