# Generated by Django 4.2.7 on 2025-07-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='payment_currency',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='stipend_amount',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='stipend_currency',
        ),
    ]
