# Generated by Django 4.2.7 on 2025-07-20 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_payment_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aplicacionproyecto",
            name="compatibility_score",
        ),
    ]
