# Generated by Django 4.2.7 on 2025-07-21 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_empresa_business_name_empresa_company_address_and_more"),
        ("projects", "0004_remove_compatibility_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyectos",
                to="companies.empresa",
            ),
        ),
    ]
