# Generated by Django 4.2.7 on 2025-08-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_proyecto_contacto_proyecto_encargado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="is_project_completion",
            field=models.BooleanField(
                default=False, help_text="Indica si el proyecto está completado"
            ),
        ),
    ]
