# Generated by Django 4.2.23 on 2025-07-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBackup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_name', models.CharField(max_length=200)),
                ('backup_type', models.CharField(default='full', max_length=50)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Respaldo de Datos',
                'verbose_name_plural': 'Respaldos de Datos',
                'db_table': 'data_backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
