# Generated by Django 3.2.23 on 2025-06-20 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('description', models.TextField(verbose_name='Descripción del Trabajo')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_hours', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='projects.project', verbose_name='Proyecto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Horas de Trabajo',
                'verbose_name_plural': 'Horas de Trabajo',
                'ordering': ['-date', '-start_time'],
                'unique_together': {('student', 'project', 'date', 'start_time')},
            },
        ),
    ]
