# Generated by Django 4.2.23 on 2025-01-27 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_consolidated'),
        ('projects', '0001_initial_consolidated'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('development', 'Desarrollo'), ('research', 'Investigación'), ('meeting', 'Reunión'), ('documentation', 'Documentación'), ('testing', 'Pruebas'), ('other', 'Otro')], default='development', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hours', to='users.user')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('is_project_completion', models.BooleanField(default=False, help_text='Indica si estas horas son para completar un proyecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='users.user')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_hours', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'Hora de Trabajo',
                'verbose_name_plural': 'Horas de Trabajo',
                'db_table': 'work_hours',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
