# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_aplicacion_options_and_more'),
        ('companies', '0003_rename_persona_contacto_empresa_city_and_more'),
        ('projects', '0003_alter_proyecto_options_and_more'),
        ('students', '0002_alter_estudiante_options_remove_estudiante_bio_and_more'),
        ('work_hours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horas_trabajadas', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado_validacion', models.CharField(default='pendiente', max_length=20)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('comentario_validacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='applications.asignacion')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='companies.empresa')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='projects.proyecto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='students.estudiante')),
                ('validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hora Trabajada',
                'verbose_name_plural': 'Horas Trabajadas',
                'db_table': 'work_hours',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='WorkHours',
        ),
    ]
