# Generated by Django 4.2.7 on 2025-08-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_hours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhour",
            name="is_project_completion",
            field=models.BooleanField(
                default=False, verbose_name="Horas de completación de proyecto"
            ),
        ),
    ]
