# Generated by Django 4.2.7 on 2025-08-02 21:14

from django.db import migrations

def update_work_hour_verification(apps, schema_editor):
    """Actualizar horas de trabajo que tienen descripción de validadas"""
    WorkHour = apps.get_model('work_hours', 'WorkHour')
    User = apps.get_model('users', 'User')
    
    # Obtener usuario admin
    admin_user = User.objects.filter(role='admin').first()
    
    # Actualizar horas de trabajo que tienen "validadas" en la descripción
    work_hours = WorkHour.objects.filter(
        is_verified=False,
        description__icontains='validadas'
    )
    
    for wh in work_hours:
        wh.is_verified = True
        wh.verified_by = admin_user
        wh.save()

def reverse_update_work_hour_verification(apps, schema_editor):
    """Revertir la actualización"""
    WorkHour = apps.get_model('work_hours', 'WorkHour')
    WorkHour.objects.filter(description__icontains='validadas').update(is_verified=False, verified_by=None)

class Migration(migrations.Migration):

    dependencies = [
        ('work_hours', '0002_add_is_project_completion'),
    ]

    operations = [
        migrations.RunPython(update_work_hour_verification, reverse_update_work_hour_verification),
    ]
