# Generated by Django 4.2.7 on 2025-07-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_hours", "0003_add_is_project_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="workhour",
            name="integrantes_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Lista de integrantes del proyecto al momento de validar",
                null=True,
            ),
        ),
    ]
