# Generated by Django 4.2.7 on 2025-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_hours", "0005_fix_hours_worked_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workhour",
            name="hours_worked",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Horas trabajadas"
            ),
        ),
        migrations.AlterModelTable(
            name="workhour",
            table="work_hours",
        ),
    ]
