# Generated by Django 4.2.7 on 2025-08-19 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "default_view",
                    models.CharField(
                        choices=[
                            ("month", "Mes"),
                            ("week", "Semana"),
                            ("day", "Día"),
                            ("agenda", "Agenda"),
                        ],
                        default="week",
                        max_length=20,
                    ),
                ),
                ("work_start_time", models.TimeField(default="09:00")),
                ("work_end_time", models.TimeField(default="18:00")),
                ("work_days", models.TextField(default="[1,2,3,4,5]")),
                ("default_reminder_minutes", models.PositiveIntegerField(default=15)),
                ("enable_notifications", models.BooleanField(default=True)),
                ("show_public_events", models.BooleanField(default=True)),
                ("allow_event_invites", models.BooleanField(default=True)),
                ("event_colors", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Calendario",
                "verbose_name_plural": "Configuraciones de Calendario",
                "db_table": "calendar_settings",
                "unique_together": {("user",)},
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Reunión"),
                            ("deadline", "Fecha Límite"),
                            ("reminder", "Recordatorio"),
                            ("interview", "Entrevista"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("normal", "Normal"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programado"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                            ("postponed", "Pospuesto"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("is_all_day", models.BooleanField(default=False)),
                ("is_online", models.BooleanField(default=False)),
                ("meeting_url", models.URLField(blank=True, null=True)),
                (
                    "meeting_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("online", "Online"),
                            ("cowork", "Cowork"),
                            ("fablab", "FabLab"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("meeting_link", models.URLField(blank=True, null=True)),
                (
                    "meeting_room",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "representative_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representative_position",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurrence_rule", models.TextField(default="{}")),
                ("reminder_minutes", models.PositiveIntegerField(default=15)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("color", models.CharField(default="#1976d2", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attended_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="projects.proyecto",
                    ),
                ),
                (
                    "related_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="applications.aplicacion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Calendario",
                "verbose_name_plural": "Eventos de Calendario",
                "db_table": "calendar_events",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_date"],
                        name="calendar_ev_user_id_15e156_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="calendar_ev_event_t_25cdb4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="calendar_ev_status_453150_idx"
                    ),
                ],
            },
        ),
    ]
