# Generated by Django 3.2.23 on 2025-06-20 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('MEETING', 'Reunión'), ('DEADLINE', 'Fecha Límite'), ('MILESTONE', 'Hito'), ('PRESENTATION', 'Presentación'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Evento')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('color', models.CharField(default='#3788d8', max_length=7, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_events', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['start_date'],
            },
        ),
    ]
