# Generated by Django 4.2.23 on 2025-07-02 00:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('postponed', 'Pospuesto')], default='scheduled', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(default='{}')),
                ('reminder_minutes', models.PositiveIntegerField(default=15)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('color', models.CharField(default='#1976d2', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'db_table': 'calendar_events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_view', models.CharField(choices=[('month', 'Mes'), ('week', 'Semana'), ('day', 'Día'), ('agenda', 'Agenda')], default='week', max_length=20)),
                ('work_start_time', models.TimeField(default='09:00')),
                ('work_end_time', models.TimeField(default='18:00')),
                ('work_days', models.TextField(default='[1,2,3,4,5]')),
                ('default_reminder_minutes', models.PositiveIntegerField(default=15)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('show_public_events', models.BooleanField(default=True)),
                ('allow_event_invites', models.BooleanField(default=True)),
                ('event_colors', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Calendario',
                'verbose_name_plural': 'Configuraciones de Calendario',
                'db_table': 'calendar_settings',
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('push', 'Notificación Push'), ('sms', 'SMS'), ('in_app', 'En la Aplicación')], max_length=10)),
                ('minutes_before', models.PositiveIntegerField(default=15)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendar_events.calendarevent')),
            ],
            options={
                'verbose_name': 'Recordatorio de Evento',
                'verbose_name_plural': 'Recordatorios de Eventos',
                'db_table': 'event_reminders',
                'ordering': ['scheduled_for'],
            },
        ),
    ]
