# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['-start_date'], 'verbose_name': 'Evento de Calendario', 'verbose_name_plural': 'Eventos de Calendario'},
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='all_day',
            new_name='is_all_day',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='related_project',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(default='general', max_length=50),
        ),
        # migrations.AlterField(
        #     model_name='calendarevent',
        #     name='id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarsettings',
            name='event_colors',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='calendarsettings',
            name='work_days',
            field=models.TextField(default='[1,2,3,4,5]'),
        ),
    ]
