# Generated by Django 4.2.23 on 2025-07-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0003_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
