# Generated by Django 4.2.23 on 2025-07-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('message', models.TextField(help_text='Contenido de la notificación')),
                ('notification_type', models.CharField(choices=[('announcement', 'Anuncio'), ('reminder', 'Recordatorio'), ('alert', 'Alerta'), ('update', 'Actualización'), ('event', 'Evento'), ('deadline', 'Fecha límite')], default='announcement', help_text='Tipo de notificación', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', help_text='Prioridad de la notificación', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('cancelled', 'Cancelada'), ('failed', 'Fallida')], default='draft', help_text='Estado de la notificación', max_length=20)),
                ('target_all_students', models.BooleanField(default=False, help_text='Enviar a todos los estudiantes')),
                ('target_all_companies', models.BooleanField(default=False, help_text='Enviar a todas las empresas')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Fecha y hora programada para el envío', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Fecha y hora cuando se envió', null=True)),
                ('total_recipients', models.IntegerField(default=0, help_text='Total de destinatarios')),
                ('sent_count', models.IntegerField(default=0, help_text='Número de notificaciones enviadas')),
                ('failed_count', models.IntegerField(default=0, help_text='Número de notificaciones fallidas')),
                ('read_count', models.IntegerField(default=0, help_text='Número de notificaciones leídas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notificación Masiva',
                'verbose_name_plural': 'Notificaciones Masivas',
                'db_table': 'mass_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notification_type', models.CharField(default='announcement', max_length=30)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación Masiva',
                'verbose_name_plural': 'Plantillas de Notificaciones Masivas',
                'db_table': 'notification_templates_mass',
                'ordering': ['-created_at'],
            },
        ),
    ]
