# Generated by Django 4.2.7 on 2025-08-19 03:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("interview_date", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("no-show", "No se presentó"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("technical", "Técnica"),
                            ("behavioral", "Comportamental"),
                            ("video", "Video"),
                            ("phone", "Teléfono"),
                            ("onsite", "Presencial"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="applications.aplicacion",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrevista",
                "verbose_name_plural": "Entrevistas",
                "db_table": "interviews",
                "ordering": ["-interview_date"],
            },
        ),
    ]
