# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_rename_persona_contacto_empresa_city_and_more'),
        ('students', '0002_alter_estudiante_options_remove_estudiante_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('message', models.TextField(help_text='Contenido de la notificación')),
                ('notification_type', models.CharField(choices=[('announcement', 'Anuncio'), ('reminder', 'Recordatorio'), ('alert', 'Alerta'), ('update', 'Actualización'), ('event', 'Evento'), ('deadline', 'Fecha límite')], default='announcement', help_text='Tipo de notificación', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', help_text='Prioridad de la notificación', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('cancelled', 'Cancelada'), ('failed', 'Fallida')], default='draft', help_text='Estado de la notificación', max_length=20)),
                ('target_all_students', models.BooleanField(default=False, help_text='Enviar a todos los estudiantes')),
                ('target_all_companies', models.BooleanField(default=False, help_text='Enviar a todas las empresas')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Fecha y hora programada para el envío', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Fecha y hora cuando se envió', null=True)),
                ('total_recipients', models.IntegerField(default=0, help_text='Total de destinatarios')),
                ('sent_count', models.IntegerField(default=0, help_text='Número de notificaciones enviadas')),
                ('failed_count', models.IntegerField(default=0, help_text='Número de notificaciones fallidas')),
                ('read_count', models.IntegerField(default=0, help_text='Número de notificaciones leídas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='mass_notifications_created', to=settings.AUTH_USER_MODEL)),
                ('target_companies', models.ManyToManyField(blank=True, help_text='Empresas destinatarias', related_name='mass_notifications_received', to='companies.empresa')),
                ('target_students', models.ManyToManyField(blank=True, help_text='Estudiantes destinatarios', related_name='mass_notifications_received', to='students.estudiante')),
            ],
            options={
                'verbose_name': 'Notificación Masiva',
                'verbose_name_plural': 'Notificaciones Masivas',
                'db_table': 'mass_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notification_type', models.CharField(default='announcement', max_length=30)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación Masiva',
                'verbose_name_plural': 'Plantillas de Notificaciones Masivas',
                'db_table': 'notification_templates_mass',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'notification_type')},
            },
        ),
    ]
