# Generated by Django 4.2.7 on 2025-08-02 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("subject", models.CharField(max_length=200, verbose_name="Asunto")),
                ("content", models.TextField(verbose_name="Cuerpo del mensaje")),
                (
                    "template_type",
                    models.CharField(
                        default="email", max_length=20, verbose_name="Tipo de plantilla"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de notificación",
                "verbose_name_plural": "Plantillas de notificaciones",
                "db_table": "mass_notifications_notificationtemplate",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MassNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "Todos los usuarios"),
                            ("students", "Solo estudiantes"),
                            ("companies", "Solo empresas"),
                            ("admins", "Solo administradores"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Audiencia objetivo",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Programado para"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado el"
                    ),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Enviado")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mass_notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación masiva",
                "verbose_name_plural": "Notificaciones masivas",
                "db_table": "mass_notifications_massnotification",
                "ordering": ["-created_at"],
            },
        ),
    ]
