# Generated by Django 4.2.23 on 2025-01-27 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_consolidated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('announcement', 'Anuncio'), ('reminder', 'Recordatorio'), ('update', 'Actualización'), ('event', 'Evento'), ('other', 'Otro')], default='announcement', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'Todos'), ('students', 'Estudiantes'), ('companies', 'Empresas'), ('admins', 'Administradores'), ('mentors', 'Mentores')], default='all', max_length=20)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('event_capacity', models.IntegerField(blank=True, null=True, help_text='Capacidad máxima para eventos')),
                ('event_date', models.DateTimeField(blank=True, null=True, help_text='Fecha del evento')),
                ('event_location', models.CharField(blank=True, max_length=200, null=True, help_text='Ubicación del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_notifications_created', to='users.user')),
            ],
            options={
                'verbose_name': 'Notificación Masiva',
                'verbose_name_plural': 'Notificaciones Masivas',
                'db_table': 'mass_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
