# Generated by Django 4.2.7 on 2025-08-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mass_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="massnotification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Baja"),
                    ("normal", "Normal"),
                    ("medium", "Media"),
                    ("high", "Alta"),
                    ("urgent", "Urgente"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="massnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("announcement", "Anuncio"),
                    ("reminder", "Recordatorio"),
                    ("alert", "Alerta"),
                    ("update", "Actualización"),
                    ("event", "Evento"),
                    ("deadline", "Fecha límite"),
                ],
                default="announcement",
                max_length=20,
                verbose_name="Tipo de notificación",
            ),
        ),
    ]
