# Generated by Django 4.2.23 on 2025-07-02 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mass_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='massnotification',
            name='created_by',
            field=models.ForeignKey(help_text='Usuario que creó la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='mass_notifications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='massnotification',
            name='target_companies',
            field=models.ManyToManyField(blank=True, help_text='Empresas destinatarias', related_name='mass_notifications_received', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='massnotification',
            name='target_students',
            field=models.ManyToManyField(blank=True, help_text='Estudiantes destinatarios', related_name='mass_notifications_received', to='students.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('name', 'notification_type')},
        ),
    ]
