# Generated by Django 4.2.7 on 2025-07-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massnotification',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', help_text='Prioridad de la notificación', max_length=20),
        ),
    ]
