# Generated by Django 4.2.7 on 2025-08-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mass_notifications", "0003_auto_20250809_2220"),
    ]

    operations = [
        migrations.AddField(
            model_name="massnotification",
            name="event_capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Capacidad del evento"
            ),
        ),
        migrations.AddField(
            model_name="massnotification",
            name="event_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha del evento"
            ),
        ),
        migrations.AddField(
            model_name="massnotification",
            name="event_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción detallada del evento"
            ),
        ),
        migrations.AddField(
            model_name="massnotification",
            name="event_location",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Ubicación del evento",
            ),
        ),
        migrations.AddField(
            model_name="massnotification",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("workshop", "Taller"),
                    ("conference", "Conferencia"),
                    ("networking", "Networking"),
                    ("presentation", "Presentación"),
                    ("meeting", "Reunión"),
                    ("other", "Otro"),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo de evento",
            ),
        ),
    ]
