# Generated by Django 4.2.23 on 2025-07-02 01:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En Revisión'), ('interviewed', 'Entrevistado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado'), ('completed', 'Completado')], default='pending', max_length=20)),
                ('compatibility_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('company_notes', models.TextField(blank=True, null=True)),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('portfolio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('github_url', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=500, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'db_table': 'applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tareas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='en curso', max_length=20)),
                ('hours_worked', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='applications.aplicacion')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'application_assignments',
            },
        ),
    ]
