# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('ENTREVISTA_PROGRAMADA', 'Entrevista Programada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('RETIRADA', 'Retirada')], default='PENDIENTE', max_length=25, verbose_name='Estado')),
                ('carta_presentacion', models.TextField(blank=True, verbose_name='Carta de Presentación')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'aplicaciones',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
