# Generated by Django 3.2.23 on 2025-06-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulación')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('UNDER_REVIEW', 'En Revisión'), ('INTERVIEW_SCHEDULED', 'Entrevista Programada'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('WITHDRAWN', 'Retirada')], default='PENDING', max_length=25, verbose_name='Estado')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Carta de Presentación')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-application_date'],
            },
        ),
    ]
