# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('projects', '0002_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_estudiante', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_estudiante', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacion',
            unique_together={('proyecto', 'estudiante')},
        ),
    ]
