# Generated by Django 4.2.23 on 2025-07-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='students.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacion',
            unique_together={('project', 'student')},
        ),
    ]
