# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('projects', '0002_initial'),
        ('students', '0002_alter_estudiante_options_remove_estudiante_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacion',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Aplicación', 'verbose_name_plural': 'Aplicaciones'},
        ),
        # migrations.AlterUniqueTogether(
        #     name='aplicacion',
        #     unique_together={('proyecto', 'estudiante')},
        # ),
        migrations.AddField(
            model_name='aplicacion',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='company_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='compatibility_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='github_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_project', to='projects.proyecto'),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En Revisión'), ('interviewed', 'Entrevistado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado'), ('completed', 'Completado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='students.estudiante'),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='student_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.AlterField(
        #     model_name='aplicacion',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        migrations.AlterModelTable(
            name='aplicacion',
            table='applications',
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tareas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='en curso', max_length=20)),
                ('hours_worked', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='applications.aplicacion')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'application_assignments',
            },
        ),
        migrations.RemoveField(
            model_name='aplicacion',
            name='carta_presentacion',
        ),
        migrations.RemoveField(
            model_name='aplicacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='aplicacion',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='aplicacion',
            name='fecha_aplicacion',
        ),
        migrations.RemoveField(
            model_name='aplicacion',
            name='proyecto',
        ),
    ]
