# Generated by Django 3.2.23 on 2025-06-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_application_project'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('project', 'student')},
        ),
    ]
