# Generated by Django 4.2.7 on 2025-07-20 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aplicacion",
            name="compatibility_score",
        ),
    ]
