# Generated by Django 4.2.23 on 2025-07-01 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_estudiante_options_remove_estudiante_bio_and_more'),
        ('projects', '0003_alter_proyecto_options_and_more'),
        ('applications', '0003_alter_aplicacion_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aplicacion',
            unique_together={('project', 'student')},
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
