# Generated by Django 4.2.7 on 2025-01-08 23:09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('student_to_company', 'Estudiante a Empresa'), ('company_to_student', 'Empresa a Estudiante'), ('student_to_project', 'Estudiante a Proyecto'), ('company_to_project', 'Empresa a Proyecto')], max_length=20, verbose_name='Tipo de calificación')),
                ('rating_value', models.IntegerField(help_text='Calificación del 1 al 5', verbose_name='Valor de calificación')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'ratings_rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCompanyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings_received', to='companies.empresa', verbose_name='Empresa')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_company_ratings', to='projects.proyecto', verbose_name='Proyecto')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_company_ratings', to='ratings.rating', verbose_name='Calificación')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ratings_given', to='students.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Calificación de estudiante a empresa',
                'verbose_name_plural': 'Calificaciones de estudiantes a empresas',
                'db_table': 'ratings_studentcompanyrating',
            },
        ),
        migrations.CreateModel(
            name='CompanyStudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings_given', to='companies.empresa', verbose_name='Empresa')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_student_ratings', to='projects.proyecto', verbose_name='Proyecto')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_student_ratings', to='ratings.rating', verbose_name='Calificación')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ratings_received', to='students.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Calificación de empresa a estudiante',
                'verbose_name_plural': 'Calificaciones de empresas a estudiantes',
                'db_table': 'ratings_companystudentrating',
            },
        ),
        migrations.CreateModel(
            name='ProjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('overall', 'General'), ('communication', 'Comunicación'), ('quality', 'Calidad'), ('timeliness', 'Puntualidad'), ('collaboration', 'Colaboración')], default='overall', max_length=20, verbose_name='Categoría')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='projects.proyecto', verbose_name='Proyecto')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Calificado por')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ratings', to='ratings.rating', verbose_name='Calificación')),
            ],
            options={
                'verbose_name': 'Calificación de proyecto',
                'verbose_name_plural': 'Calificaciones de proyectos',
                'db_table': 'ratings_projectrating',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together={('project', 'rated_by', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='companystudentrating',
            unique_together={('company', 'student', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcompanyrating',
            unique_together={('student', 'company', 'project')},
        ),
    ] 