# Generated by Django 4.2.7 on 2025-07-14 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_estudiante_education_level_estudiante_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLevelRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('current_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_level_requests', to='students.estudiante')),
            ],
            options={
                'verbose_name': 'Petición de Nivel API',
                'verbose_name_plural': 'Peticiones de Nivel API',
                'db_table': 'api_level_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
