# Generated by Django 4.2.7 on 2025-08-13 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0010_remove_rating_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="hours_per_week",
            field=models.IntegerField(
                default=20,
                help_text="Horas semanales disponibles para proyectos",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(35),
                ],
            ),
        ),
    ]
