# Generated by Django 4.2.7 on 2025-08-13 17:39

from django.db import migrations


def populate_hours_per_week_default(apps, schema_editor):
    """Establece el valor por defecto de 20 en hours_per_week para registros existentes"""
    Estudiante = apps.get_model('students', 'Estudiante')
    
    # Actualizar todos los estudiantes que tengan NULL en hours_per_week
    estudiantes_actualizados = Estudiante.objects.filter(hours_per_week__isnull=True).update(hours_per_week=20)
    
    print(f"✅ [MIGRATION] Actualizados {estudiantes_actualizados} estudiantes con hours_per_week=20")


def reverse_populate_hours_per_week_default(apps, schema_editor):
    """Revierte la migración (no es necesario hacer nada)"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0012_remove_estudiante_graduation_year_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_hours_per_week_default,
            reverse_populate_hours_per_week_default
        ),
    ]
