# Generated by Django 5.2.3 on 2025-06-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del área', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del área', null=True)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal del área', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icono del área', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['name'],
            },
        ),
    ]
