# Generated by Django 4.2.23 on 2025-07-02 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('contract', 'Contrato'), ('proposal', 'Propuesta'), ('report', 'Reporte'), ('presentation', 'Presentación'), ('manual', 'Manual'), ('certificate', 'Certificado'), ('other', 'Otro')], default='other', help_text='Tipo de documento', max_length=20)),
                ('file', models.FileField(help_text='Archivo del documento', upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'jpg', 'jpeg', 'png'])])),
                ('file_url', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0, help_text='Número de descargas del documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
