# Generated by Django 4.2.23 on 2025-07-02 00:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntuacion', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('comunicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('flexibilidad', models.PositiveIntegerField(blank=True, null=True)),
                ('aprendizaje', models.PositiveIntegerField(blank=True, null=True)),
                ('ambiente_trabajo', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calificación de Empresa',
                'verbose_name_plural': 'Calificaciones de Empresas',
                'db_table': 'company_ratings',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande'), ('Startup', 'Startup')], max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_projects', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('total_hours_offered', models.IntegerField(default=0)),
                ('technologies_used', models.TextField(blank=True, null=True)),
                ('benefits_offered', models.TextField(blank=True, null=True)),
                ('remote_work_policy', models.CharField(blank=True, choices=[('full-remote', 'Full Remote'), ('hybrid', 'Híbrido'), ('onsite', 'Presencial')], max_length=50, null=True)),
                ('internship_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('stipend_range', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('suspended', 'Suspendida')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies',
            },
        ),
    ]
