# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntuacion', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('comunicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('flexibilidad', models.PositiveIntegerField(blank=True, null=True)),
                ('aprendizaje', models.PositiveIntegerField(blank=True, null=True)),
                ('ambiente_trabajo', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calificación de Empresa',
                'verbose_name_plural': 'Calificaciones de Empresas',
                'db_table': 'company_ratings',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('tamaño', models.CharField(choices=[('startup', 'Startup'), ('pequena', 'Pequeña (1-50)'), ('mediana', 'Mediana (51-200)'), ('grande', 'Grande (201-1000)'), ('corporacion', 'Corporación (1000+)')], default='mediana', max_length=20)),
                ('industria', models.CharField(choices=[('tecnologia', 'Tecnología'), ('finanzas', 'Finanzas'), ('salud', 'Salud'), ('educacion', 'Educación'), ('retail', 'Retail'), ('manufactura', 'Manufactura'), ('consultoria', 'Consultoría'), ('marketing', 'Marketing'), ('diseno', 'Diseño'), ('otros', 'Otros')], default='tecnologia', max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('año_fundacion', models.PositiveIntegerField(blank=True, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_calificaciones', models.PositiveIntegerField(default=0)),
                ('proyectos_publicados', models.PositiveIntegerField(default=0)),
                ('proyectos_completados', models.PositiveIntegerField(default=0)),
                ('esta_verificada', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('redes_sociales', models.JSONField(default=dict)),
                ('beneficios', models.JSONField(default=list)),
                ('tecnologias', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies',
            },
        ),
    ]
