# Generated by Django 3.2.23 on 2025-06-28 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacionempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='calificacionempresa',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='calificacionempresa',
            unique_together={('empresa', 'estudiante')},
        ),
    ]
