# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='persona_contacto',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='email_contacto',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='telefono_contacto',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='calificacion_promedio',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='esta_verificada',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='año_fundacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='beneficios',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_verificacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='industria',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='proyectos_completados',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='proyectos_publicados',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='redes_sociales',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='sitio_web',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tamaño',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tecnologias',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='total_calificaciones',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='benefits_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='internship_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='projects_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='remote_work_policy',
            field=models.CharField(blank=True, choices=[('full-remote', 'Full Remote'), ('hybrid', 'Híbrido'), ('onsite', 'Presencial')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='size',
            field=models.CharField(blank=True, choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande'), ('Startup', 'Startup')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('suspended', 'Suspendida')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stipend_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='technologies_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='total_hours_offered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
