# Generated by Django 4.2.7 on 2025-08-10 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mass_notifications", "0002_massnotification_priority_and_more"),
    ]

    operations = []
