# Generated by Django 5.2.3 on 2025-06-30 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_rename_persona_contacto_empresa_city_and_more'),
        ('students', '0002_alter_estudiante_options_remove_estudiante_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_date', models.DateField(help_text='Fecha del incidente')),
                ('description', models.TextField(help_text='Descripción detallada del incidente')),
                ('action_taken', models.TextField(blank=True, help_text='Acción disciplinaria tomada', null=True)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', help_text='Severidad del incidente', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='Empresa donde ocurrió el incidente', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='companies.empresa')),
                ('recorded_by', models.ForeignKey(help_text='Usuario que registró el incidente', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Estudiante involucrado en el incidente', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='students.estudiante')),
            ],
            options={
                'verbose_name': 'Registro Disciplinario',
                'verbose_name_plural': 'Registros Disciplinarios',
                'db_table': 'disciplinary_records',
                'ordering': ['-incident_date'],
            },
        ),
    ]
