# Generated by Django 4.2.23 on 2025-07-02 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_date', models.DateField(help_text='Fecha del incidente')),
                ('description', models.TextField(help_text='Descripción detallada del incidente')),
                ('action_taken', models.TextField(blank=True, help_text='Acción disciplinaria tomada', null=True)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', help_text='Severidad del incidente', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='Empresa donde ocurrió el incidente', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Registro Disciplinario',
                'verbose_name_plural': 'Registros Disciplinarios',
                'db_table': 'disciplinary_records',
                'ordering': ['-incident_date'],
            },
        ),
    ]
