# Generated by Django 4.2.23 on 2025-07-02 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplinary_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='recorded_by',
            field=models.ForeignKey(help_text='Usuario que registró el incidente', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='student',
            field=models.ForeignKey(help_text='Estudiante involucrado en el incidente', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='students.estudiante'),
        ),
    ]
