# Generated by Django 4.2.7 on 2025-08-06 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_empresa_business_name_empresa_company_address_and_more"),
        ("students", "0009_change_student_status_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("disciplinary_records", "0002_auto_20250805_1437"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disciplinaryrecords",
            options={
                "ordering": ["-recorded_at"],
                "verbose_name": "Registro Disciplinario",
                "verbose_name_plural": "Registros Disciplinarios",
            },
        ),
        migrations.RemoveField(
            model_name="disciplinaryrecords",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="disciplinaryrecords",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="disciplinaryrecords",
            name="name",
        ),
        migrations.RemoveField(
            model_name="disciplinaryrecords",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="disciplinaryrecords",
            name="action_taken",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disciplinaryrecords",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinary_records",
                to="companies.empresa",
            ),
        ),
        migrations.AddField(
            model_name="disciplinaryrecords",
            name="incident_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="disciplinaryrecords",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="disciplinaryrecords",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinary_records_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="disciplinaryrecords",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Baja"),
                    ("medium", "Media"),
                    ("high", "Alta"),
                    ("critical", "Crítica"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="disciplinaryrecords",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disciplinary_records",
                to="students.estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryrecords",
            name="description",
            field=models.TextField(default="Sin descripción"),
        ),
        migrations.AlterField(
            model_name="disciplinaryrecords",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="disciplinaryrecords",
            table="disciplinary_records",
        ),
    ]
