# Generated by Django 4.2.7 on 2025-08-19 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TRLLevel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "level",
                    models.IntegerField(
                        help_text="Nivel TRL del 1 al 9",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre del nivel TRL", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del nivel",
                        null=True,
                    ),
                ),
                (
                    "min_hours",
                    models.IntegerField(
                        help_text="Horas mínimas requeridas para este nivel"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nivel TRL",
                "verbose_name_plural": "Niveles TRL",
                "db_table": "trl_levels",
                "ordering": ["level"],
            },
        ),
    ]
