# Generated by Django 4.2.23 on 2025-01-27 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRLLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('criteria', models.TextField(help_text='Criterios para alcanzar este nivel TRL')),
                ('examples', models.TextField(blank=True, null=True, help_text='Ejemplos de proyectos en este nivel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel TRL',
                'verbose_name_plural': 'Niveles TRL',
                'db_table': 'trl_levels',
                'ordering': ['level'],
            },
        ),
    ]
