# Generated by Django 4.2.23 on 2025-01-27 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial_consolidated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('user_management', 'Gestión de Usuarios'), ('system_config', 'Configuración del Sistema'), ('data_export', 'Exportación de Datos'), ('backup', 'Respaldo'), ('maintenance', 'Mantenimiento'), ('other', 'Otro')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to='users.user')),
            ],
            options={
                'verbose_name': 'Acción de Administrador',
                'verbose_name_plural': 'Acciones de Administrador',
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
