# Generated by Django 4.2.23 on 2025-07-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Tipo de acción realizada', max_length=100)),
                ('entity_type', models.CharField(blank=True, help_text='Tipo de entidad relacionada', max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, help_text='ID de la entidad relacionada', max_length=50, null=True)),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales de la actividad', null=True)),
                ('ip_address', models.CharField(blank=True, help_text='Dirección IP del usuario', max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent del navegador', max_length=500, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto relacionado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de contenido relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
