# Generated by Django 5.2.3 on 2025-06-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='biografia',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='esta_verificado',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='año_graduacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='calificacion_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='horas_totales',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='industria_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nivel_api',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='promedio_academico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='proyectos_completados',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sitio_web_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='strikes',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tamaño_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ubicacion_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultimo_acceso',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('student', 'Estudiante'), ('company', 'Empresa')], max_length=20),
        ),
    ]
