# Generated by Django 4.2.23 on 2025-07-02 01:37

from django.db import migrations


def activate_all_users(apps, schema_editor):
    """Activar todos los usuarios existentes y cambiar estado de estudiantes"""
    User = apps.get_model('users', 'User')
    Estudiante = apps.get_model('students', 'Estudiante')
    
    # Activar todos los usuarios
    User.objects.all().update(is_active=True, is_verified=True)
    
    # Cambiar estado de todos los estudiantes de 'pending' a 'approved'
    Estudiante.objects.filter(status='pending').update(status='approved')
    
    print(f"✅ Usuarios activados: {User.objects.filter(is_active=True).count()}")
    print(f"✅ Estudiantes aprobados: {Estudiante.objects.filter(status='approved').count()}")


def reverse_activate_all_users(apps, schema_editor):
    """Revertir la activación de usuarios"""
    User = apps.get_model('users', 'User')
    Estudiante = apps.get_model('students', 'Estudiante')
    
    # Desactivar usuarios (excepto admins)
    User.objects.filter(role__in=['student', 'company']).update(is_active=False, is_verified=False)
    
    # Cambiar estado de estudiantes de vuelta a 'pending'
    Estudiante.objects.filter(status='approved').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_birthdate_user_gender'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(activate_all_users, reverse_activate_all_users),
    ]
