# Generated by Django 4.2.7 on 2025-01-08 23:04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.proyecto', verbose_name='Proyecto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'assignments_assignment',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name='Nombre del rol')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Responsabilidades')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='assignments.assignment', verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'Rol de asignación',
                'verbose_name_plural': 'Roles de asignación',
                'db_table': 'assignments_assignmentrole',
            },
        ),
        migrations.CreateModel(
            name='AssignmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('overdue', 'Atrasado')], default='pending', max_length=20, verbose_name='Estado')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='assignments.assignment', verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'Hito de asignación',
                'verbose_name_plural': 'Hitos de asignación',
                'db_table': 'assignments_assignmentmilestone',
                'ordering': ['due_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('student', 'project')},
        ),
    ] 